### ISSUE TITLE
Query parameter to search for quotes without certain characters

### ISSUE THREAD

**Issue by eben-vranken** [lukePeavey/quotable#102] opened 2021-12-28 14:55 UTC
## Description

I'm currently building a [typing game](https://github.com/eben-vranken/typerless) that's powered by this API.
But there is one issue: Sometimes the API generates a Quote with a special apostrophe that requires an alt code to write.
Currently, I do have an in-code fix, but would be nice to have a GET request with this feature.

**Comment by raxraj** [comment] 2022-01-02 07:18
@lukePeavey,
Are we looking into this.
This seems to be a legit add-on.

**Comment by lukePeavey** [comment] 2022-01-05 00:46
Hey, sorry just seeing this now.  Yes, we can definitely look into a fix for this. 

Just to clarify, what special character are you referring to?

**Comment by eben-vranken** [comment] 2022-01-05 08:54
The character I'm referring to is: ’

**Comment by lukePeavey** [comment] 2022-01-07 18:53
That's weird... there are 58 of those in the quotes collection.  I am going to replace them with a regular single quote character.

**Comment by lukePeavey** [comment] 2022-01-07 18:55
Are there any other special characters that are causing problems in your app?

**Comment by lukePeavey** [comment] 2022-01-07 18:58
If you would like to look at the complete source data for the API, its available here: 

https://github.com/quotable-io/data

**Comment by eben-vranken** [comment] 2022-01-07 18:58
No that was it! Thanks

**Comment by lukePeavey** [comment] 2022-01-07 18:58
Cool I'll let you know once I fix that

**Comment by lukePeavey** [comment] 2022-01-07 19:09
Fixed (see b1e2bf127ab65343d4301dac02d498926dcad48c). 

Just synced changes with database, should be live now.

**Comment by lukePeavey** [comment] 2022-01-07 19:48
Do you think we still need a filter param to get quotes without certain chars or does this resolves the issue? 

CC @raxraj

**Comment by raxraj** [comment] 2022-01-07 19:52
Issue is resolved
That's great. 

@lukePeavey 
I was thinking of some sort Word filter.
Like where the user might not want a specific word to be appearing on quotes. 

I will create a separate issue with the whole idea and the concept on how we can do it.

We can close this one.

**Comment by lukePeavey** [comment] 2022-01-07 22:59
@raxraj sounds good

**Comment by lukePeavey** [comment] 2022-01-07 23:12
@eben-vranken let me know when you have tested this out. If the issue is resolved on your end we can close.

**Comment by eben-vranken** [comment] 2022-01-07 23:20
Im going to review it later, i'll keep you updated

**Comment by lukePeavey** [comment] 2022-01-14 11:16
@eben-vranken I'm going to close this. Feel free to re-open the issue if you have an additional problems.

**Closed** 2022-01-14 11:16 UTC
Labels: :zap: type: enhancement, :heavy_check_mark:  status: fixed
