### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by mgon123** [lukePeavey/quotable#142] opened 2022-08-30 19:17 UTC
Attempting to use this for a bootcamp project, but it seems to be down. Will it be coming back up soon?

**Comment by emmahsax** [comment] 2022-09-01 02:30
Duplicate of https://github.com/lukePeavey/quotable/issues/143.

Also can confirm that the API is down for me. 
![image](https://user-images.githubusercontent.com/7562793/187819518-a2a8cc86-1752-4e4e-aea2-7889d12f4d83.png)

**Comment by lukePeavey** [comment] 2022-09-06 03:10
# Fixed

**Closed** 2022-09-27 06:30 UTC
Labels: :heavy_check_mark:  status: fixed, :warning: API is down
